### YamlMime:Yaml
ms.openlocfilehash: 349d99e777196280f64585ec571e6e83e70c2e70
ms.sourcegitcommit: e33dc94c1a64cb6a7b5c40ca6886fefa6865c9d0
ms.translationtype: MT
ms.contentlocale: zh-CN
ms.lasthandoff: 05/14/2022
ms.locfileid: "12513934"
blank_issues_enabled: true
contact_links:
- name: DevTools 问题
  url: https://docs.microsoft.com/microsoft-edge/devtools-guide-chromium/contact
  about: Learn more about how to submit feature requests or bug reports about Microsoft Edge DevTools.
- name: WebView2 问题
  url: https://github.com/MicrosoftEdge/WebView2Feedback/issues
  about: Use the WebView2Feedback repository to report feedback, submit feature suggestions or bugs about WebView2, search for existing known issues for WebView2, or share tips and best practices.
